source 'git@github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

def common
    pod 'Alamofire', '~> 4.4'
    pod 'DGElasticPullToRefresh'
    pod 'FillableLoaders', '~>1.3.0'
    pod 'Kingfisher'
    pod 'ReachabilitySwift', '~> 3'
    pod 'SQLite.swift'
    pod 'SnapKit', '~> 3.2.0'
    pod 'StarWars', '~> 2.0'
    pod 'SwiftyJSON'
    pod 'MBProgressHUD'
end

target 'SmartHomeI' do
    common
end
